# Generated by Django 4.1.3 on 2022-12-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('Individual Entrepreneur', 'Individual Entrepreneur'), ('Dealership', 'Dealership'), ('Retail Network', 'Retail Network'), ('Distributor', 'Distributor'), ('Factory', 'Factory')], default='Factory', max_length=50),
        ),
    ]
