# Generated by Django 4.1.3 on 2022-12-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rocket_app', '0003_alter_element_type_alter_employee_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('Individual Entrepreneur', 'Individual Entrepreneur'), ('Retail Network', 'Retail Network'), ('Distributor', 'Distributor'), ('Dealership', 'Dealership'), ('Factory', 'Factory')], default='Factory', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='rocket_app.element'),
        ),
    ]
