# Generated by Django 4.1.3 on 2022-12-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocket_app', '0004_alter_element_type_alter_employee_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('Factory', 'Factory'), ('Distributor', 'Distributor'), ('Dealership', 'Dealership'), ('Individual Entrepreneur', 'Individual Entrepreneur'), ('Retail Network', 'Retail Network')], default='Factory', max_length=50),
        ),
    ]
