# Generated by Django 4.1.3 on 2022-12-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rocket_app', '0006_alter_address_contact_alter_contact_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rocket_app.contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rocket_app.element', unique=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('Distributor', 'Distributor'), ('Factory', 'Factory'), ('Dealership', 'Dealership'), ('Individual Entrepreneur', 'Individual Entrepreneur'), ('Retail Network', 'Retail Network')], default='Factory', max_length=50),
        ),
    ]
